### ISSUE TITLE
I tried this out and ran across some issues that made it unusable for my purposes.

### ISSUE THREAD

**Issue by papley** [mtfourre/PrettyPrintable#1]
You might want to put a disclaimer in the readme.

I ran into a lot of crashes due to properties which are not key value coding compliant.

I converted the pod to work with MacOS as well as iOS, and perhaps some of what I saw only pertains to MacOS, but I don't think so.

If the PrettyPrintable class contains properties which are Swift enum or optional Int, you have to eliminate those properties, changing them to NSNumber or something. 

It seems that even for all properties that ARE key value compliant, they must be declared @objc dynamic to avoid a crash. Perhaps there's a workaround for that, but I couldn't find it.

Too bad, a lot of work went into this and I was hopeful it would provide a framework I could use.

**Comment by mtfourre** [comment]
Hi @papley and thank you for creating this issue. It's unfortunate that you had to run into these problems and I'm disappointed that I'm only now able to begin to address them. I made a poor assumption that GitHub would automatically notify me about open issues on my own repository, although I believe that this is not the case by default. I realize that you are certainly past the point of attempting to utilize this library, and I apologize for the significant delay in response. However, in the interest of self learning and good faith, I will do my best to follow through and provide a solution for the issues raised.

I can possibly address right now some of the points you raised:

- This library was tested exclusively on iOS, although I am confident as well with you that the issues probably exist on both MacOS and iOS.
- It is true that either the class must be Objective-C accessible or there must be a separate solution to key value compliance. In my case, I had written my own KVC solution for Swift types although as of yet that remains unpublished publicly. This does speak to the nature of Swift in its reluctancy to provide KVC although clearly the library should operate reliably regardless.
- The currently available iteration of the PrettyPrintable library unfortunately had not been updated to respond uniquely in development and production environments. This means that while although the necessity of this module exists primarily only in development, it may operate fully in production anyway and could experience the crashes described above while in the hands of the user. This is a big mistake and should have been in place from the start.

I regret that this library proved to be a time sink for you and I hope that it can be rectified in the near future. Thank you again for giving it a try and letting me know about it by opening an issue. I will begin work and aim to provide an update which at least reduces or removes the tendency for crashes and optimally provides a solution for printing relevant data about Swift types, although the latter is unlikely without either KVC provided from Swift or use of a separate library to fill in those gaps.

**Comment by mtfourre** [comment]
I am pleased to release an update for this module which should resolve all of the issues raised above. I have removed the KVC requirements which means that this should be usable for any object, not just those which are accessible by Objective-C. Simply adopting the `PrettyPrintable` protocol on any object will provide an improved `description` property. Additionally, the protocol conforms to CustomStringConvertible, so passing an entire object to the `print(_:)` function should automatically utilize the `PrettyPrintable` representation.

I've also added support for dictionaries where previously only arrays were supported. A `PrettyPrintable` object, when generating its `description`, should be able to traverse an arbitrary number of nested `PrettyPrintable` objects. This also works inside arrays and dictionaries, so having an array or dictionary filled with `PrettyPrintable` objects should still appear human readable in the console.

With these updates, I have removed the disclaimer in the readme. The new CocoaPods version is `0.3.0` which includes the migration away from KVC as well as support for dictionaries. I regret that the length of time from issue open to issue close is so long, though I am happy to provide a solution later rather than never. As I mentioned earlier, I don't expect you (@papley) to return to the library as the window of opportunity has passed. However, if at any point you do get a chance to look over this once more, I welcome all additional feedback. Thank you again for bringing these problems to my attention.
